<a href="https://colab.research.google.com/github/charitha0606/-assignment-python/blob/master/python12_09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

->ways of creating arrays in python

In [1]:
#1.array()
from numpy import*
arr=array([1,2,3,4])
print(arr)

[1 2 3 4]


In [3]:
#1.array()
from numpy import*
arr=array([1,2,3,4,5.0])
print(arr)
print(arr.dtype)

[1. 2. 3. 4. 5.]
float64


In [9]:
#2.linspace()
from numpy import*
a=linspace(0,10,11)
print(a)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [10]:
#3.logspace()
from numpy import*
a=logspace(1,20,5)
print(a)

[1.00000000e+01 5.62341325e+05 3.16227766e+10 1.77827941e+15
 1.00000000e+20]


In [13]:
#4.arange
from numpy import*
a=arange(0,10,2)
print(a)

[0 2 4 6 8]


In [16]:
#5.zeroes()
from numpy import*
a=zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [17]:
#6.ones()
from numpy import*
a=ones(5,int)
print(a)

[1 1 1 1 1]


->copying an array in python

In [18]:
from numpy import*
a=array([1,2,3,4,5])
a=a+5
print(a)

[ 6  7  8  9 10]


In [20]:
from numpy import*
a1=array([1,2,3,4,5])
a2=array([6,7,8,9,10])
a=a1+a2
print(a)

[ 7  9 11 13 15]


In [21]:
from numpy import*
a=array([1,2,3])
print(log(a))
print(sin(a))
print(cos(a))

[0.         0.69314718 1.09861229]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]


In [22]:
from numpy import*
a1=([1,2,3])
a2=([4,5,6])
print(concatenate([a1,a2]))

[1 2 3 4 5 6]


In [23]:
from numpy import*
a1=array([2,4,6,8,10])
a2=a1
print(a1)
print(a2)
print(id(a1))
print(id(a2))

[ 2  4  6  8 10]
[ 2  4  6  8 10]
140691445609456
140691445609456


In [24]:
from numpy import*
a1=array([2,4,6,8,10])
a2=a1.view()
print(a1)
print(a2)
print(id(a1))
print(id(a2))

[ 2  4  6  8 10]
[ 2  4  6  8 10]
140691445419344
140691445418224


alaising,view


In [25]:
#shallow copy
from numpy import*
a1=array([2,4,6,8])
a2=a1.view()
a1[1]=7
print(a1)
print(a2)
print(id(a1))
print(id(a2))

[2 7 6 8]
[2 7 6 8]
140691445310528
140691445312608


In [27]:
#deep copy
from numpy import*
a1=array([2,4,6,8])
a2=a1.copy()
a1[1]=7
print(a1)
print(a2)
print(id(a1))
print(id(a2))

[2 7 6 8]
[2 4 6 8]
140691445130704
140691445643184


->working with matrix in python

In [34]:
from numpy import*
a1=array([
          [1,2],
          [3,4]
          ])
print(a1)
a2=a1.flatten()
print(a2)

[[1 2]
 [3 4]]
[1 2 3 4]


In [37]:
from numpy import*
a1=array([
          [1,2],
          [3,4]
          ])
print(a1)
a1.dtype
a1.shape
a1.size


[[1 2]
 [3 4]]


4

In [45]:
from numpy import*
arr1=array([
            [1,2,3,4],
            [4,5,6,7]
            ])
arr2=arr1.flatten()
print(arr2)

[1 2 3 4 4 5 6 7]
